// Package vectrixdb provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package vectrixdb

// ACLSearchRequest Search with ACL/security filtering.
type ACLSearchRequest struct {
	// AclField Metadata field containing ACL
	AclField *string `json:"acl_field,omitempty"`

	// DefaultAllow Allow if no ACL defined
	DefaultAllow *bool                   `json:"default_allow,omitempty"`
	Filter       *map[string]interface{} `json:"filter,omitempty"`
	Limit        *int                    `json:"limit,omitempty"`
	Query        []float32               `json:"query"`

	// UserPrincipals User's principals e.g. ['user:alice', 'group:eng']
	UserPrincipals []string `json:"user_principals"`
}

// AccessCheckRequest defines model for AccessCheckRequest.
type AccessCheckRequest struct {
	Collection string `json:"collection"`

	// Email The address to try, as their sign-in would carry it
	Email *string `json:"email,omitempty"`

	// Groups The security group ids to try them with, standing in for the token. A store policy reads the address alone
	Groups *[]string `json:"groups,omitempty"`

	// Subject Their subject at the identity provider, when there is no address
	Subject *string `json:"subject,omitempty"`
}

// AddPointsRequest Request to add points.
type AddPointsRequest struct {
	Points []PointData `json:"points"`
}

// AddPointsRequestV2 Enhanced request to add points with text for hybrid search.
type AddPointsRequestV2 struct {
	Points []map[string]interface{} `json:"points"`
}

// AddPointsWithSparseRequest Request to add points with sparse vectors.
type AddPointsWithSparseRequest struct {
	Points []map[string]interface{} `json:"points"`
}

// AddSourceRequest defines model for AddSourceRequest.
type AddSourceRequest struct {
	// Address The feed's or the page's address.
	Address string `json:"address"`

	// Articles A feed: index the article each entry links to.
	Articles *bool `json:"articles,omitempty"`

	// DeleteWhenGone A page: remove its chunks when it answers 404 or 410.
	DeleteWhenGone *bool `json:"delete_when_gone,omitempty"`

	// Every How often it is read: 30m, 6h, 1d, or seconds.
	Every *string `json:"every,omitempty"`

	// Kind feed or page. Left out, it is fetched once to tell.
	Kind *string `json:"kind,omitempty"`

	// Transcribe A podcast: transcribe episodes when an audio extractor is configured.
	Transcribe *bool `json:"transcribe,omitempty"`
}

// BeginRequest defines model for BeginRequest.
type BeginRequest struct {
	Email string `json:"email"`
}

// CodeRequest defines model for CodeRequest.
type CodeRequest struct {
	Code string `json:"code"`
}

// ConfirmRequest defines model for ConfirmRequest.
type ConfirmRequest struct {
	Code     string  `json:"code"`
	Password *string `json:"password,omitempty"`
	Ticket   string  `json:"ticket"`
}

// CreateCollectionRequest Request to create a collection.
type CreateCollectionRequest struct {
	Description *string `json:"description,omitempty"`
	Dimension   int     `json:"dimension"`
	Metric      *string `json:"metric,omitempty"`
	Name        string  `json:"name"`

	// Tags Capability tags: Dense, Sparse, Hybrid, Ultimate, Graph
	Tags *[]string `json:"tags,omitempty"`
}

// CreateCollectionRequestV2 Enhanced request to create a collection with advanced options.
type CreateCollectionRequestV2 struct {
	Description *string `json:"description,omitempty"`
	Dimension   int     `json:"dimension"`

	// EnableTextIndex Enable hybrid search
	EnableTextIndex *bool `json:"enable_text_index,omitempty"`

	// HnswEfConstruction HNSW construction parameter
	HnswEfConstruction *int `json:"hnsw_ef_construction,omitempty"`

	// HnswM HNSW M parameter
	HnswM  *int    `json:"hnsw_m,omitempty"`
	Metric *string `json:"metric,omitempty"`
	Name   string  `json:"name"`

	// Tags Capability tags: Dense, Sparse, Hybrid, Ultimate, Graph
	Tags *[]string `json:"tags,omitempty"`
}

// CredentialRequest defines model for CredentialRequest.
type CredentialRequest struct {
	Credential map[string]interface{} `json:"credential"`
	Name       *string                `json:"name,omitempty"`
	Ticket     *string                `json:"ticket,omitempty"`
}

// DeletePointsRequest Request to delete points.
type DeletePointsRequest struct {
	Ids []string `json:"ids"`
}

// DenseSparseSearchRequest Dense + Sparse hybrid search request (Qdrant-style).
type DenseSparseSearchRequest struct {
	DenseQuery     []float32               `json:"dense_query"`
	DenseWeight    *float32                `json:"dense_weight,omitempty"`
	Filter         *map[string]interface{} `json:"filter,omitempty"`
	IncludeVectors *bool                   `json:"include_vectors,omitempty"`
	Limit          *int                    `json:"limit,omitempty"`

	// SparseQuery Sparse vector representation.
	SparseQuery  SparseVectorData `json:"sparse_query"`
	SparseWeight *float32         `json:"sparse_weight,omitempty"`
}

// EnterpriseSearchRequest Full enterprise search with all features.
type EnterpriseSearchRequest struct {
	// DefaultAllow Allow if no ACL defined
	DefaultAllow   *bool                   `json:"default_allow,omitempty"`
	Facets         *[]string               `json:"facets,omitempty"`
	Filter         *map[string]interface{} `json:"filter,omitempty"`
	Limit          *int                    `json:"limit,omitempty"`
	Query          []float32               `json:"query"`
	QueryText      *string                 `json:"query_text,omitempty"`
	Rerank         *bool                   `json:"rerank,omitempty"`
	RerankLimit    *int                    `json:"rerank_limit,omitempty"`
	RerankMethod   *string                 `json:"rerank_method,omitempty"`
	UserPrincipals *[]string               `json:"user_principals,omitempty"`
}

// FacetedSearchRequest Search with faceted aggregations.
type FacetedSearchRequest struct {
	// FacetLimit Max values per facet
	FacetLimit *int `json:"facet_limit,omitempty"`

	// Facets Fields to aggregate
	Facets *[]string               `json:"facets,omitempty"`
	Filter *map[string]interface{} `json:"filter,omitempty"`
	Limit  *int                    `json:"limit,omitempty"`
	Query  []float32               `json:"query"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// HybridSearchRequest Hybrid search request (vector + keyword).
type HybridSearchRequest struct {
	Filter            *map[string]interface{} `json:"filter,omitempty"`
	IncludeHighlights *bool                   `json:"include_highlights,omitempty"`
	IncludeVectors    *bool                   `json:"include_vectors,omitempty"`
	Limit             *int                    `json:"limit,omitempty"`
	Query             []float32               `json:"query"`
	QueryText         string                  `json:"query_text"`
	TextWeight        *float32                `json:"text_weight,omitempty"`
	VectorWeight      *float32                `json:"vector_weight,omitempty"`
}

// IndexDocumentRequest Request to index a document.
type IndexDocumentRequest struct {
	// DocType Document type: text, markdown, pdf
	DocType  *string                 `json:"doc_type,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Text     string                  `json:"text"`
	Title    *string                 `json:"title,omitempty"`
}

// KeyRequest defines model for KeyRequest.
type KeyRequest struct {
	// Collections The collections this key may reach. Left out, every collection its role allows.
	Collections *[]string `json:"collections,omitempty"`

	// ExpiresInDays How long the key works for. Left out, until it is revoked.
	ExpiresInDays *int   `json:"expires_in_days,omitempty"`
	Name          string `json:"name"`

	// RequestsPerMinute How many requests a minute the key may make. Left out, the server's VECTRIXDB_KEY_REQUESTS_PER_MINUTE, and with that unset, no limit.
	RequestsPerMinute *int   `json:"requests_per_minute,omitempty"`
	Role              string `json:"role"`
}

// KeywordSearchRequest Keyword search request (full-text).
type KeywordSearchRequest struct {
	Filter            *map[string]interface{} `json:"filter,omitempty"`
	IncludeHighlights *bool                   `json:"include_highlights,omitempty"`
	Limit             *int                    `json:"limit,omitempty"`
	QueryText         string                  `json:"query_text"`
}

// PasswordRequest defines model for PasswordRequest.
type PasswordRequest struct {
	Password string `json:"password"`
}

// PersonRequest defines model for PersonRequest.
type PersonRequest struct {
	Email     string                  `json:"email"`
	Grants    *[]interface{}          `json:"grants,omitempty"`
	Principal *map[string]interface{} `json:"principal,omitempty"`
	Role      string                  `json:"role"`
}

// PointData A single point.
type PointData struct {
	Id       string                  `json:"id"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Vector   []float32               `json:"vector"`
}

// PolicyRequest defines model for PolicyRequest.
type PolicyRequest struct {
	// Policy Who may retrieve from the collection: {"method": "token", "allow": [{"id": ..., "name": ...}], "people": [{"email": ...}]} for security groups by object id from the sign-in token, narrowed to the people on the list, who must be in a group and on it; or {"method": "store", "allow": [{"email": ...} | {"domain": ...}]} for a list of people kept with the collection. null is nobody
	Policy *map[string]interface{} `json:"policy,omitempty"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// Force Every source, not only the ones that are due.
	Force *bool `json:"force,omitempty"`

	// MaxItems Entries written per source.
	MaxItems *int `json:"max_items,omitempty"`

	// Source One source's id or address.
	Source *string `json:"source,omitempty"`
}

// RerankSearchRequest Search with re-ranking (two-stage retrieval).
type RerankSearchRequest struct {
	// DiversityLambda MMR diversity (0=diverse, 1=relevant)
	DiversityLambda *float32                `json:"diversity_lambda,omitempty"`
	Filter          *map[string]interface{} `json:"filter,omitempty"`
	Limit           *int                    `json:"limit,omitempty"`
	Query           []float32               `json:"query"`

	// QueryText For cross-encoder re-ranking
	QueryText *string `json:"query_text,omitempty"`

	// RerankLimit Candidates for re-ranking
	RerankLimit *int `json:"rerank_limit,omitempty"`

	// RerankMethod exact, mmr, cross_encoder, weighted
	RerankMethod *string `json:"rerank_method,omitempty"`
}

// ResetRequest defines model for ResetRequest.
type ResetRequest struct {
	Code     string `json:"code"`
	Password string `json:"password"`
	Token    string `json:"token"`
}

// SearchRequest Search request.
type SearchRequest struct {
	Filter         *map[string]interface{} `json:"filter,omitempty"`
	IncludeVectors *bool                   `json:"include_vectors,omitempty"`
	Limit          *int                    `json:"limit,omitempty"`
	Query          []float32               `json:"query"`
	ScoreThreshold *float32                `json:"score_threshold,omitempty"`
	UseCache       *bool                   `json:"use_cache,omitempty"`
}

// SparseSearchRequest Sparse vector search request.
type SparseSearchRequest struct {
	Filter *map[string]interface{} `json:"filter,omitempty"`
	Limit  *int                    `json:"limit,omitempty"`

	// Query Sparse vector representation.
	Query          SparseVectorData `json:"query"`
	ScoreThreshold *float32         `json:"score_threshold,omitempty"`
}

// SparseVectorData Sparse vector representation.
type SparseVectorData struct {
	// Indices Non-zero dimension indices
	Indices []int `json:"indices"`

	// Values Corresponding values
	Values []float32 `json:"values"`
}

// StepUpRequest defines model for StepUpRequest.
type StepUpRequest struct {
	Code     *string `json:"code,omitempty"`
	Password *string `json:"password,omitempty"`
}

// TextSearchRequest Text-based semantic search request.
//
// The server embeds the text with the model the library writes vectors
// with by default, bge-small-en-v1.5, so no vectors need computing.
type TextSearchRequest struct {
	Filter         *map[string]interface{} `json:"filter,omitempty"`
	IncludeVectors *bool                   `json:"include_vectors,omitempty"`
	Limit          *int                    `json:"limit,omitempty"`

	// QueryText Search query text (auto-embedded)
	QueryText string `json:"query_text"`

	// Rerank Re-rank the top candidates with the bundled cross-encoder. The dashboard used to send this and the server ignored it, so its Rerank mode was dense search.
	Rerank         *bool    `json:"rerank,omitempty"`
	ScoreThreshold *float32 `json:"score_threshold,omitempty"`
	UseCache       *bool    `json:"use_cache,omitempty"`
}

// TextUpsertPoint Point with text for auto-embedding.
type TextUpsertPoint struct {
	// Id Point ID
	Id string `json:"id"`

	// Payload Additional metadata
	Payload *map[string]interface{} `json:"payload,omitempty"`

	// Text Text to embed and store
	Text string `json:"text"`
}

// TextUpsertRequest Request for text upsert endpoint.
type TextUpsertRequest struct {
	// Points Points with text to embed
	Points []TextUpsertPoint `json:"points"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{} `json:"ctx,omitempty"`
	Input interface{}             `json:"input,omitempty"`
	Loc   []interface{}           `json:"loc"`
	Msg   string                  `json:"msg"`
	Type  string                  `json:"type"`
}

// VerifyRequest defines model for VerifyRequest.
type VerifyRequest struct {
	Code     string  `json:"code"`
	Email    string  `json:"email"`
	Password *string `json:"password,omitempty"`
}

// AccessLogApiV1AccessGetParams defines parameters for AccessLogApiV1AccessGet.
type AccessLogApiV1AccessGetParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Event  *string `form:"event,omitempty" json:"event,omitempty"`
	Who    *string `form:"who,omitempty" json:"who,omitempty"`
}

// AccessDailyApiV1AccessDailyGetParams defines parameters for AccessDailyApiV1AccessDailyGet.
type AccessDailyApiV1AccessDailyGetParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// AccessReadersApiV1AccessReadersGetParams defines parameters for AccessReadersApiV1AccessReadersGet.
type AccessReadersApiV1AccessReadersGetParams struct {
	Days   *int    `form:"days,omitempty" json:"days,omitempty"`
	Top    *int    `form:"top,omitempty" json:"top,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
}

// AuditTrailApiV1AuditGetParams defines parameters for AuditTrailApiV1AuditGet.
type AuditTrailApiV1AuditGetParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Q A find: records that hold this in their collection, principal, outcome or id.
	Q          *string `form:"q,omitempty" json:"q,omitempty"`
	Collection *string `form:"collection,omitempty" json:"collection,omitempty"`

	// Days How many days the counts a day and by collection go back.
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ListChunkingApiV1ChunkingGetParams defines parameters for ListChunkingApiV1ChunkingGet.
type ListChunkingApiV1ChunkingGetParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// AddDocumentApiV1CollectionsNameDocumentsPostParams defines parameters for AddDocumentApiV1CollectionsNameDocumentsPost.
type AddDocumentApiV1CollectionsNameDocumentsPostParams struct {
	// DocId The document's id. The file's name when left out.
	DocId        *string `form:"doc_id,omitempty" json:"doc_id,omitempty"`
	Chunk        *string `form:"chunk,omitempty" json:"chunk,omitempty"`
	ChunkSize    *int    `form:"chunk_size,omitempty" json:"chunk_size,omitempty"`
	Overlap      *int    `form:"overlap,omitempty" json:"overlap,omitempty"`
	EmbedHeading *bool   `form:"embed_heading,omitempty" json:"embed_heading,omitempty"`

	// Metadata A JSON object put on every chunk.
	Metadata     *string `form:"metadata,omitempty" json:"metadata,omitempty"`
	OnLowQuality *string `form:"on_low_quality,omitempty" json:"on_low_quality,omitempty"`
}

// GetDocumentApiV1CollectionsNameDocumentsDocIdGetParams defines parameters for GetDocumentApiV1CollectionsNameDocumentsDocIdGet.
type GetDocumentApiV1CollectionsNameDocumentsDocIdGetParams struct {
	// Raw With the front matter.
	Raw *bool `form:"raw,omitempty" json:"raw,omitempty"`
}

// GetCollectionGraphApiV1CollectionsNameGraphGetParams defines parameters for GetCollectionGraphApiV1CollectionsNameGraphGet.
type GetCollectionGraphApiV1CollectionsNameGraphGetParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CollectionGrowthApiV1CollectionsNameGrowthGetParams defines parameters for CollectionGrowthApiV1CollectionsNameGrowthGet.
type CollectionGrowthApiV1CollectionsNameGrowthGetParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ListPointsApiV1CollectionsNamePointsGetParams defines parameters for ListPointsApiV1CollectionsNamePointsGet.
type ListPointsApiV1CollectionsNamePointsGetParams struct {
	Limit  *int  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int  `form:"offset,omitempty" json:"offset,omitempty"`
	Index  *bool `form:"index,omitempty" json:"index,omitempty"`

	// Q A find: points whose id, or source when the chunks are kept, holds this.
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// ChunkProvenanceApiV1CollectionsNameProvenancePointIdGetParams defines parameters for ChunkProvenanceApiV1CollectionsNameProvenancePointIdGet.
type ChunkProvenanceApiV1CollectionsNameProvenancePointIdGetParams struct {
	Text *bool `form:"text,omitempty" json:"text,omitempty"`
}

// CollectionQualityApiV1CollectionsNameQualityGetParams defines parameters for CollectionQualityApiV1CollectionsNameQualityGet.
type CollectionQualityApiV1CollectionsNameQualityGetParams struct {
	Threshold *float32 `form:"threshold,omitempty" json:"threshold,omitempty"`
	Worst     *int     `form:"worst,omitempty" json:"worst,omitempty"`
	Offset    *int     `form:"offset,omitempty" json:"offset,omitempty"`
	Text      *bool    `form:"text,omitempty" json:"text,omitempty"`
}

// RefreshSourcesApiV1CollectionsNameSourcesRefreshPostJSONBody defines parameters for RefreshSourcesApiV1CollectionsNameSourcesRefreshPost.
type RefreshSourcesApiV1CollectionsNameSourcesRefreshPostJSONBody = RefreshRequest

// RemoveSourceApiV1CollectionsNameSourcesSourceIdDeleteParams defines parameters for RemoveSourceApiV1CollectionsNameSourcesSourceIdDelete.
type RemoveSourceApiV1CollectionsNameSourcesSourceIdDeleteParams struct {
	// DeleteDocuments Take the documents it wrote too, unless another source wrote them.
	DeleteDocuments *bool `form:"delete_documents,omitempty" json:"delete_documents,omitempty"`
}

// ListDocumentsApiV1DocumentsGetParams defines parameters for ListDocumentsApiV1DocumentsGet.
type ListDocumentsApiV1DocumentsGetParams struct {
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetDocumentChunksApiV1DocumentsDocIdChunksGetParams defines parameters for GetDocumentChunksApiV1DocumentsDocIdChunksGet.
type GetDocumentChunksApiV1DocumentsDocIdChunksGetParams struct {
	ChunkSize *int `form:"chunk_size,omitempty" json:"chunk_size,omitempty"`
}

// ListEvaluationsApiV1EvaluationsGetParams defines parameters for ListEvaluationsApiV1EvaluationsGet.
type ListEvaluationsApiV1EvaluationsGetParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GrowthApiV1GrowthGetParams defines parameters for GrowthApiV1GrowthGet.
type GrowthApiV1GrowthGetParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// PeopleAuthPeopleGetParams defines parameters for PeopleAuthPeopleGet.
type PeopleAuthPeopleGetParams struct {
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// AccessCheckApiV1AccessCheckPostJSONRequestBody defines body for AccessCheckApiV1AccessCheckPost for application/json ContentType.
type AccessCheckApiV1AccessCheckPostJSONRequestBody = AccessCheckRequest

// CreateCollectionApiV1CollectionsPostJSONRequestBody defines body for CreateCollectionApiV1CollectionsPost for application/json ContentType.
type CreateCollectionApiV1CollectionsPostJSONRequestBody = CreateCollectionRequest

// DenseSparseSearchApiV1CollectionsNameDenseSparseSearchPostJSONRequestBody defines body for DenseSparseSearchApiV1CollectionsNameDenseSparseSearchPost for application/json ContentType.
type DenseSparseSearchApiV1CollectionsNameDenseSparseSearchPostJSONRequestBody = DenseSparseSearchRequest

// HybridSearchApiV1CollectionsNameHybridSearchPostJSONRequestBody defines body for HybridSearchApiV1CollectionsNameHybridSearchPost for application/json ContentType.
type HybridSearchApiV1CollectionsNameHybridSearchPostJSONRequestBody = HybridSearchRequest

// KeywordSearchApiV1CollectionsNameKeywordSearchPostJSONRequestBody defines body for KeywordSearchApiV1CollectionsNameKeywordSearchPost for application/json ContentType.
type KeywordSearchApiV1CollectionsNameKeywordSearchPostJSONRequestBody = KeywordSearchRequest

// DeletePointsApiV1CollectionsNamePointsDeleteJSONRequestBody defines body for DeletePointsApiV1CollectionsNamePointsDelete for application/json ContentType.
type DeletePointsApiV1CollectionsNamePointsDeleteJSONRequestBody = DeletePointsRequest

// AddPointsApiV1CollectionsNamePointsPostJSONRequestBody defines body for AddPointsApiV1CollectionsNamePointsPost for application/json ContentType.
type AddPointsApiV1CollectionsNamePointsPostJSONRequestBody = AddPointsRequest

// SetPolicyApiV1CollectionsNamePolicyPutJSONRequestBody defines body for SetPolicyApiV1CollectionsNamePolicyPut for application/json ContentType.
type SetPolicyApiV1CollectionsNamePolicyPutJSONRequestBody = PolicyRequest

// SearchApiV1CollectionsNameSearchPostJSONRequestBody defines body for SearchApiV1CollectionsNameSearchPost for application/json ContentType.
type SearchApiV1CollectionsNameSearchPostJSONRequestBody = SearchRequest

// SearchWithAclApiV1CollectionsNameSearchAclPostJSONRequestBody defines body for SearchWithAclApiV1CollectionsNameSearchAclPost for application/json ContentType.
type SearchWithAclApiV1CollectionsNameSearchAclPostJSONRequestBody = ACLSearchRequest

// EnterpriseSearchApiV1CollectionsNameSearchEnterprisePostJSONRequestBody defines body for EnterpriseSearchApiV1CollectionsNameSearchEnterprisePost for application/json ContentType.
type EnterpriseSearchApiV1CollectionsNameSearchEnterprisePostJSONRequestBody = EnterpriseSearchRequest

// SearchWithFacetsApiV1CollectionsNameSearchFacetsPostJSONRequestBody defines body for SearchWithFacetsApiV1CollectionsNameSearchFacetsPost for application/json ContentType.
type SearchWithFacetsApiV1CollectionsNameSearchFacetsPostJSONRequestBody = FacetedSearchRequest

// SearchWithRerankApiV1CollectionsNameSearchRerankPostJSONRequestBody defines body for SearchWithRerankApiV1CollectionsNameSearchRerankPost for application/json ContentType.
type SearchWithRerankApiV1CollectionsNameSearchRerankPostJSONRequestBody = RerankSearchRequest

// AddSourceApiV1CollectionsNameSourcesPostJSONRequestBody defines body for AddSourceApiV1CollectionsNameSourcesPost for application/json ContentType.
type AddSourceApiV1CollectionsNameSourcesPostJSONRequestBody = AddSourceRequest

// RefreshSourcesApiV1CollectionsNameSourcesRefreshPostJSONRequestBody defines body for RefreshSourcesApiV1CollectionsNameSourcesRefreshPost for application/json ContentType.
type RefreshSourcesApiV1CollectionsNameSourcesRefreshPostJSONRequestBody = RefreshSourcesApiV1CollectionsNameSourcesRefreshPostJSONBody

// SparseSearchApiV1CollectionsNameSparseSearchPostJSONRequestBody defines body for SparseSearchApiV1CollectionsNameSparseSearchPost for application/json ContentType.
type SparseSearchApiV1CollectionsNameSparseSearchPostJSONRequestBody = SparseSearchRequest

// TextHybridSearchApiV1CollectionsNameTextHybridSearchPostJSONRequestBody defines body for TextHybridSearchApiV1CollectionsNameTextHybridSearchPost for application/json ContentType.
type TextHybridSearchApiV1CollectionsNameTextHybridSearchPostJSONRequestBody = TextSearchRequest

// TextSearchApiV1CollectionsNameTextSearchPostJSONRequestBody defines body for TextSearchApiV1CollectionsNameTextSearchPost for application/json ContentType.
type TextSearchApiV1CollectionsNameTextSearchPostJSONRequestBody = TextSearchRequest

// TextUpsertApiV1CollectionsNameTextUpsertPostJSONRequestBody defines body for TextUpsertApiV1CollectionsNameTextUpsertPost for application/json ContentType.
type TextUpsertApiV1CollectionsNameTextUpsertPostJSONRequestBody = TextUpsertRequest

// IndexDocumentApiV1DocumentsPostJSONRequestBody defines body for IndexDocumentApiV1DocumentsPost for application/json ContentType.
type IndexDocumentApiV1DocumentsPostJSONRequestBody = IndexDocumentRequest

// CreateKeyApiV1KeysPostJSONRequestBody defines body for CreateKeyApiV1KeysPost for application/json ContentType.
type CreateKeyApiV1KeysPostJSONRequestBody = KeyRequest

// CreateCollectionV2ApiV2CollectionsPostJSONRequestBody defines body for CreateCollectionV2ApiV2CollectionsPost for application/json ContentType.
type CreateCollectionV2ApiV2CollectionsPostJSONRequestBody = CreateCollectionRequestV2

// AddPointsV2ApiV2CollectionsNamePointsPostJSONRequestBody defines body for AddPointsV2ApiV2CollectionsNamePointsPost for application/json ContentType.
type AddPointsV2ApiV2CollectionsNamePointsPostJSONRequestBody = AddPointsRequestV2

// AddPointsWithSparseApiV2CollectionsNamePointsSparsePostJSONRequestBody defines body for AddPointsWithSparseApiV2CollectionsNamePointsSparsePost for application/json ContentType.
type AddPointsWithSparseApiV2CollectionsNamePointsSparsePostJSONRequestBody = AddPointsWithSparseRequest

// EmailBeginAuthEmailBeginPostJSONRequestBody defines body for EmailBeginAuthEmailBeginPost for application/json ContentType.
type EmailBeginAuthEmailBeginPostJSONRequestBody = BeginRequest

// EnrolBeginAuthEmailEnrolBeginPostJSONRequestBody defines body for EnrolBeginAuthEmailEnrolBeginPost for application/json ContentType.
type EnrolBeginAuthEmailEnrolBeginPostJSONRequestBody = TokenRequest

// EnrolConfirmAuthEmailEnrolConfirmPostJSONRequestBody defines body for EnrolConfirmAuthEmailEnrolConfirmPost for application/json ContentType.
type EnrolConfirmAuthEmailEnrolConfirmPostJSONRequestBody = ConfirmRequest

// EmailVerifyAuthEmailVerifyPostJSONRequestBody defines body for EmailVerifyAuthEmailVerifyPost for application/json ContentType.
type EmailVerifyAuthEmailVerifyPostJSONRequestBody = VerifyRequest

// ReplaceAuthenticatorConfirmAuthMeAuthenticatorConfirmPostJSONRequestBody defines body for ReplaceAuthenticatorConfirmAuthMeAuthenticatorConfirmPost for application/json ContentType.
type ReplaceAuthenticatorConfirmAuthMeAuthenticatorConfirmPostJSONRequestBody = CodeRequest

// AddPasskeyFinishAuthMePasskeysFinishPostJSONRequestBody defines body for AddPasskeyFinishAuthMePasskeysFinishPost for application/json ContentType.
type AddPasskeyFinishAuthMePasskeysFinishPostJSONRequestBody = CredentialRequest

// SetMyPasswordAuthMePasswordPostJSONRequestBody defines body for SetMyPasswordAuthMePasswordPost for application/json ContentType.
type SetMyPasswordAuthMePasswordPostJSONRequestBody = PasswordRequest

// PasskeyEnrolBeginAuthPasskeyEnrolBeginPostJSONRequestBody defines body for PasskeyEnrolBeginAuthPasskeyEnrolBeginPost for application/json ContentType.
type PasskeyEnrolBeginAuthPasskeyEnrolBeginPostJSONRequestBody = TokenRequest

// PasskeyEnrolFinishAuthPasskeyEnrolFinishPostJSONRequestBody defines body for PasskeyEnrolFinishAuthPasskeyEnrolFinishPost for application/json ContentType.
type PasskeyEnrolFinishAuthPasskeyEnrolFinishPostJSONRequestBody = CredentialRequest

// PasskeyFinishAuthPasskeyFinishPostJSONRequestBody defines body for PasskeyFinishAuthPasskeyFinishPost for application/json ContentType.
type PasskeyFinishAuthPasskeyFinishPostJSONRequestBody = CredentialRequest

// PasswordForgotAuthPasswordForgotPostJSONRequestBody defines body for PasswordForgotAuthPasswordForgotPost for application/json ContentType.
type PasswordForgotAuthPasswordForgotPostJSONRequestBody = BeginRequest

// PasswordResetAuthPasswordResetPostJSONRequestBody defines body for PasswordResetAuthPasswordResetPost for application/json ContentType.
type PasswordResetAuthPasswordResetPostJSONRequestBody = ResetRequest

// PutPersonAuthPeoplePostJSONRequestBody defines body for PutPersonAuthPeoplePost for application/json ContentType.
type PutPersonAuthPeoplePostJSONRequestBody = PersonRequest

// StepUpAuthStepUpPostJSONRequestBody defines body for StepUpAuthStepUpPost for application/json ContentType.
type StepUpAuthStepUpPostJSONRequestBody = StepUpRequest

// StepUpPasskeyFinishAuthStepUpPasskeyFinishPostJSONRequestBody defines body for StepUpPasskeyFinishAuthStepUpPasskeyFinishPost for application/json ContentType.
type StepUpPasskeyFinishAuthStepUpPasskeyFinishPostJSONRequestBody = CredentialRequest
