"""Collections written by 2.1.7 open with 2.2 and can be repaired.

tests/fixtures/legacy_2_1_7 was generated by the 2.1.7 code (git HEAD before
this release, run from a worktree) with the bundled English model, which is
the model 2.2 resolves to by default. Two collections are in it:

* `saved`: the user called save, so an index file exists.
* `unsaved`: the common case. 2.1.7 never persisted the index on add(), so
  the rows are in SQLite, the vectors survive only as the store's copy, and
  a search finds nothing. `rebuild_index()` recovers it from that copy.
"""

import shutil
from pathlib import Path

import pytest

from vectrixdb import Vectrix

FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "legacy_2_1_7"


@pytest.fixture
def legacy(tmp_path):
    """A copy, so the fixture in the repo is never modified."""
    target = tmp_path / "legacy"
    shutil.copytree(FIXTURE, target)
    return target


class TestSaved:
    def test_opens_with_rows_text_and_metadata(self, legacy):
        db = Vectrix("saved", path=str(legacy))
        assert db.count() == 6
        hit = db.search("radium", limit=1).top
        assert "radium" in hit.text.lower()
        assert hit.metadata["topic"] == "science"

    def test_json_vectors_are_read_and_can_be_compacted(self, legacy):
        db = Vectrix("saved", path=str(legacy))
        storage = db._db._storage
        moved = storage.compact_vectors("saved")
        assert moved == 6, "2.1.7 stored every vector as JSON; all six should move"
        assert storage.compact_vectors("saved") == 0
        assert db.search("basalt", limit=1).top.text.startswith("Basalt")

    def test_can_keep_writing(self, legacy):
        db = Vectrix("saved", path=str(legacy))
        db.add("A seventh document about glaciers.")
        assert db.count() == 7
        assert db.search("glaciers", limit=1).top.text.startswith("A seventh")


class TestUnsaved:
    def test_rows_survive_but_search_is_empty(self, legacy):
        db = Vectrix("unsaved", path=str(legacy))
        assert db.count() == 6
        assert len(db.search("radium", limit=3)) == 0, "no index was ever written by 2.1.7"

    def test_rebuild_recovers_search_from_the_stored_copies(self, legacy):
        db = Vectrix("unsaved", path=str(legacy))
        assert db.rebuild_index() == 6
        hit = db.search("radium", limit=1).top
        assert "radium" in hit.text.lower()

        reopened = Vectrix("unsaved", path=str(legacy))
        assert reopened.search("sourdough", limit=1).top.text.startswith("Sourdough")
